// ============================================================
//  CertifyPro — Certification Roadmap Data Engine
//  Covers 6 domains × 30+ certifications with full metadata
// ============================================================

export const DOMAINS = [
    {
        id: 'cloud',
        label: 'Cloud Engineering',
        icon: '☁️',
        color: '#0ea5e9',
        gradient: 'linear-gradient(135deg,#0ea5e9,#06b6d4)',
        description: 'AWS, Azure, GCP — from practitioner to architect',
    },
    {
        id: 'security',
        label: 'Cybersecurity',
        icon: '🔐',
        color: '#f43f5e',
        gradient: 'linear-gradient(135deg,#f43f5e,#e11d48)',
        description: 'Protect systems, networks and data end-to-end',
    },
    {
        id: 'data',
        label: 'Data & Analytics',
        icon: '📊',
        color: '#8b5cf6',
        gradient: 'linear-gradient(135deg,#8b5cf6,#6d28d9)',
        description: 'Engineering, analytics, warehousing and ML pipelines',
    },
    {
        id: 'devops',
        label: 'DevOps & Platform',
        icon: '⚙️',
        color: '#f59e0b',
        gradient: 'linear-gradient(135deg,#f59e0b,#d97706)',
        description: 'CI/CD, containers, IaC, site reliability',
    },
    {
        id: 'webdev',
        label: 'Web Development',
        icon: '🌐',
        color: '#10b981',
        gradient: 'linear-gradient(135deg,#10b981,#059669)',
        description: 'JavaScript, frameworks, full-stack and backend',
    },
    {
        id: 'aiml',
        label: 'AI & Machine Learning',
        icon: '🤖',
        color: '#a855f7',
        gradient: 'linear-gradient(135deg,#a855f7,#7c3aed)',
        description: 'ML foundations through MLOps and generative AI',
    },
];

// Difficulty: 1=Beginner  2=Intermediate  3=Advanced  4=Expert
export const CERT_DB = {
    // ──────────────── CLOUD ────────────────
    'aws-ccp': {
        id: 'aws-ccp',
        name: 'AWS Cloud Practitioner',
        issuer: 'Amazon Web Services',
        domain: 'cloud',
        level: 1,
        durationMonths: 1,
        cost: '$100',
        examCode: 'CLF-C02',
        prerequisites: [],
        next: ['aws-saa', 'aws-dva'],
        advanced: ['aws-sap', 'aws-dop'],
        optional: ['azure-fundamentals', 'gcp-ace'],
        skills: ['AWS core services','IAM basics','Cloud billing','EC2/S3/RDS overview'],
        careerOutcome: 'Entry point for cloud roles; shows foundational cloud literacy',
        jobRoles: ['Cloud Intern', 'Solutions Engineer (Entry)', 'Technical Sales'],
        avgSalary: '₹4–7 LPA',
    },
    'aws-saa': {
        id: 'aws-saa',
        name: 'AWS Solutions Architect Associate',
        issuer: 'Amazon Web Services',
        domain: 'cloud',
        level: 2,
        durationMonths: 2,
        cost: '$150',
        examCode: 'SAA-C03',
        prerequisites: ['aws-ccp'],
        next: ['aws-sap', 'aws-dop'],
        advanced: ['aws-sec', 'cka'],
        optional: ['terraform'],
        skills: ['VPC design','High Availability','Auto Scaling','RDS/DynamoDB','Cost optimisation'],
        careerOutcome: 'Most in-demand AWS cert; opens architect and senior cloud roles',
        jobRoles: ['Cloud Architect', 'Solutions Architect', 'Cloud Engineer'],
        avgSalary: '₹10–18 LPA',
    },
    'aws-sap': {
        id: 'aws-sap',
        name: 'AWS Solutions Architect Professional',
        issuer: 'Amazon Web Services',
        domain: 'cloud',
        level: 4,
        durationMonths: 3,
        cost: '$300',
        examCode: 'SAP-C02',
        prerequisites: ['aws-saa'],
        next: ['aws-sec'],
        advanced: [],
        optional: ['gcp-pca'],
        skills: ['Complex multi-account architectures','Hybrid cloud','Advanced networking','Cost governance'],
        careerOutcome: 'Senior/Principal architect roles; leads org-wide cloud strategy',
        jobRoles: ['Principal Cloud Architect', 'VP Engineering', 'Enterprise Architect'],
        avgSalary: '₹22–40 LPA',
    },
    'aws-dop': {
        id: 'aws-dop',
        name: 'AWS DevOps Professional',
        issuer: 'Amazon Web Services',
        domain: 'cloud',
        level: 3,
        durationMonths: 3,
        cost: '$300',
        examCode: 'DOP-C02',
        prerequisites: ['aws-saa'],
        next: ['cka', 'aws-sec'],
        advanced: [],
        optional: ['terraform'],
        skills: ['CI/CD on AWS','CloudFormation','Incident management','Monitoring & observability'],
        careerOutcome: 'Bridge between devops and cloud; required for SRE/platform teams',
        jobRoles: ['Cloud DevOps Engineer', 'SRE', 'Platform Engineer'],
        avgSalary: '₹15–25 LPA',
    },
    'aws-sec': {
        id: 'aws-sec',
        name: 'AWS Security Specialty',
        issuer: 'Amazon Web Services',
        domain: 'cloud',
        level: 4,
        durationMonths: 3,
        cost: '$300',
        examCode: 'SCS-C02',
        prerequisites: ['aws-saa'],
        next: [],
        advanced: [],
        optional: ['cissp'],
        skills: ['KMS','GuardDuty','Security Hub','IAM advanced','Compliance frameworks'],
        careerOutcome: 'Security engineering on AWS; pairs well with CISSP for total security leadership',
        jobRoles: ['Cloud Security Engineer', 'Security Architect'],
        avgSalary: '₹18–30 LPA',
    },
    'azure-fundamentals': {
        id: 'azure-fundamentals',
        name: 'Azure Fundamentals (AZ-900)',
        issuer: 'Microsoft',
        domain: 'cloud',
        level: 1,
        durationMonths: 1,
        cost: '$165',
        examCode: 'AZ-900',
        prerequisites: [],
        next: ['azure-administrator', 'azure-developer'],
        advanced: ['azure-architect'],
        optional: ['aws-ccp'],
        skills: ['Azure core services','Pricing & SLAs','Governance','Identity basics'],
        careerOutcome: 'Entry into Microsoft cloud; widely required in enterprise IT',
        jobRoles: ['IT Admin', 'Cloud Sales', 'Junior Cloud Engineer'],
        avgSalary: '₹4–8 LPA',
    },
    'azure-administrator': {
        id: 'azure-administrator',
        name: 'Azure Administrator (AZ-104)',
        issuer: 'Microsoft',
        domain: 'cloud',
        level: 2,
        durationMonths: 2,
        cost: '$165',
        examCode: 'AZ-104',
        prerequisites: ['azure-fundamentals'],
        next: ['azure-architect'],
        advanced: ['azure-security'],
        optional: ['aws-saa'],
        skills: ['Resource management','Networking','Storage','Azure AD','VM management'],
        careerOutcome: 'Core administrator cert; required in most enterprise cloud teams',
        jobRoles: ['Azure Administrator', 'Cloud Support Engineer', 'Sysadmin'],
        avgSalary: '₹8–14 LPA',
    },
    'azure-architect': {
        id: 'azure-architect',
        name: 'Azure Solutions Architect Expert',
        issuer: 'Microsoft',
        domain: 'cloud',
        level: 4,
        durationMonths: 3,
        cost: '$165',
        examCode: 'AZ-305',
        prerequisites: ['azure-administrator'],
        next: [],
        advanced: [],
        optional: ['aws-sap'],
        skills: ['Identity & governance','Data storage design','Infrastructure','Monitor & optimize'],
        careerOutcome: 'Expert-level Azure; leads architecture reviews and migration projects',
        jobRoles: ['Azure Architect', 'Enterprise Architect', 'Cloud Consultant'],
        avgSalary: '₹20–35 LPA',
    },
    'gcp-ace': {
        id: 'gcp-ace',
        name: 'Google Cloud Associate Engineer',
        issuer: 'Google Cloud',
        domain: 'cloud',
        level: 2,
        durationMonths: 2,
        cost: '$200',
        examCode: 'ACE',
        prerequisites: [],
        next: ['gcp-pca'],
        advanced: ['gcp-de'],
        optional: ['aws-saa'],
        skills: ['GKE','Cloud Run','VPC','IAM','Deployment manager'],
        careerOutcome: 'In-demand for GCP-focused orgs; pairs well with Kubernetes',
        jobRoles: ['Cloud Engineer', 'GCP Consultant', 'Platform Engineer'],
        avgSalary: '₹10–16 LPA',
    },
    'gcp-pca': {
        id: 'gcp-pca',
        name: 'Google Professional Cloud Architect',
        issuer: 'Google Cloud',
        domain: 'cloud',
        level: 3,
        durationMonths: 3,
        cost: '$200',
        examCode: 'PCA',
        prerequisites: ['gcp-ace'],
        next: [],
        advanced: [],
        optional: ['aws-sap'],
        skills: ['Hybrid architectures','Security design','Data & storage solutions','Reliability'],
        careerOutcome: 'Senior GCP architect; commands premium salaries in GCP-heavy orgs',
        jobRoles: ['GCP Architect', 'Principal Engineer', 'Cloud Consultant'],
        avgSalary: '₹18–32 LPA',
    },

    // ──────────────── SECURITY ────────────────
    'sec-plus': {
        id: 'sec-plus',
        name: 'CompTIA Security+',
        issuer: 'CompTIA',
        domain: 'security',
        level: 1,
        durationMonths: 2,
        cost: '$370',
        examCode: 'SY0-701',
        prerequisites: [],
        next: ['ceh', 'cissp'],
        advanced: ['oscp', 'ccsp'],
        optional: ['aws-sec'],
        skills: ['Threats & attacks','Cryptography','Network security','Compliance & policies'],
        careerOutcome: 'Baseline security cert; DoD 8570 approved; required in govt/defence',
        jobRoles: ['Security Analyst', 'SOC Analyst', 'IT Security Specialist'],
        avgSalary: '₹6–12 LPA',
    },
    'ceh': {
        id: 'ceh',
        name: 'Certified Ethical Hacker (CEH)',
        issuer: 'EC-Council',
        domain: 'security',
        level: 2,
        durationMonths: 2,
        cost: '$950',
        examCode: 'CEH v12',
        prerequisites: ['sec-plus'],
        next: ['oscp', 'cissp'],
        advanced: ['ccsp'],
        optional: ['aws-sec'],
        skills: ['Pen testing methodology','Footprinting','Exploitation','Malware analysis','Social engineering'],
        careerOutcome: 'Entry into offensive security; widely recognised in Asian markets',
        jobRoles: ['Ethical Hacker', 'Penetration Tester', 'Security Consultant'],
        avgSalary: '₹8–16 LPA',
    },
    'cissp': {
        id: 'cissp',
        name: 'Certified Information Systems Security Professional',
        issuer: 'ISC²',
        domain: 'security',
        level: 4,
        durationMonths: 6,
        cost: '$699',
        examCode: 'CISSP',
        prerequisites: ['sec-plus', 'ceh'],
        next: [],
        advanced: [],
        optional: ['ccsp'],
        skills: ['Security governance','Risk management','Asset security','Identity management','Software security'],
        careerOutcome: 'Gold standard security cert; required for CISO and security leadership',
        jobRoles: ['CISO', 'Security Director', 'Security Architect'],
        avgSalary: '₹25–50 LPA',
    },
    'oscp': {
        id: 'oscp',
        name: 'Offensive Security Certified Professional',
        issuer: 'Offensive Security',
        domain: 'security',
        level: 4,
        durationMonths: 4,
        cost: '$1499',
        examCode: 'PEN-200',
        prerequisites: ['ceh'],
        next: [],
        advanced: [],
        optional: ['cissp'],
        skills: ['Buffer overflows','Privilege escalation','Exploit development','Active Directory attacks','Report writing'],
        careerOutcome: 'Most respected hands-on pen testing cert; opens red team roles worldwide',
        jobRoles: ['Red Team Operator', 'Senior Pen Tester', 'Exploit Developer'],
        avgSalary: '₹18–40 LPA',
    },
    'ccsp': {
        id: 'ccsp',
        name: 'Certified Cloud Security Professional',
        issuer: 'ISC²',
        domain: 'security',
        level: 3,
        durationMonths: 3,
        cost: '$599',
        examCode: 'CCSP',
        prerequisites: ['cissp'],
        next: [],
        advanced: [],
        optional: ['aws-sec'],
        skills: ['Cloud architecture security','Data security','Platform & infrastructure security','GRC for cloud'],
        careerOutcome: 'Bridges cloud and security; highly valued in financial and healthcare sectors',
        jobRoles: ['Cloud Security Architect', 'GRC Analyst', 'CISO (cloud focus)'],
        avgSalary: '₹20–38 LPA',
    },

    // ──────────────── DATA ────────────────
    'gcp-de': {
        id: 'gcp-de',
        name: 'Google Professional Data Engineer',
        issuer: 'Google Cloud',
        domain: 'data',
        level: 3,
        durationMonths: 3,
        cost: '$200',
        examCode: 'PDE',
        prerequisites: ['gcp-ace'],
        next: ['databricks-de', 'aws-da'],
        advanced: ['azure-da'],
        optional: ['snowpro'],
        skills: ['BigQuery','Dataflow','Data Studio','ML on GCP','Pub/Sub','Data pipelines'],
        careerOutcome: 'Top data engineering cert; leads to principal DE and data architect roles',
        jobRoles: ['Data Engineer', 'Analytics Engineer', 'Data Architect'],
        avgSalary: '₹14–24 LPA',
    },
    'databricks-de': {
        id: 'databricks-de',
        name: 'Databricks Certified Data Engineer',
        issuer: 'Databricks',
        domain: 'data',
        level: 3,
        durationMonths: 2,
        cost: '$200',
        examCode: 'Associate',
        prerequisites: [],
        next: ['gcp-de', 'aws-da'],
        advanced: ['azure-da'],
        optional: ['snowpro'],
        skills: ['Apache Spark','Delta Lake','Lakehouse architecture','ETL with PySpark','Streaming'],
        careerOutcome: 'Highly sought-after in modern data stack companies; opens lakehouse engineering',
        jobRoles: ['Data Engineer', 'Spark Developer', 'Lakehouse Engineer'],
        avgSalary: '₹12–22 LPA',
    },
    'aws-da': {
        id: 'aws-da',
        name: 'AWS Data Analytics Specialty',
        issuer: 'Amazon Web Services',
        domain: 'data',
        level: 3,
        durationMonths: 3,
        cost: '$300',
        examCode: 'DAS-C01',
        prerequisites: ['aws-saa'],
        next: [],
        advanced: [],
        optional: ['databricks-de'],
        skills: ['Kinesis','Redshift','EMR','Glue','Athena','QuickSight'],
        careerOutcome: 'Specialized analytics on AWS; pairs with data engineering career paths',
        jobRoles: ['Data Architect', 'Analytics Engineer', 'BI Engineer'],
        avgSalary: '₹16–26 LPA',
    },
    'snowpro': {
        id: 'snowpro',
        name: 'SnowPro Core Certification',
        issuer: 'Snowflake',
        domain: 'data',
        level: 2,
        durationMonths: 1,
        cost: '$175',
        examCode: 'SnowPro Core',
        prerequisites: [],
        next: ['databricks-de'],
        advanced: ['gcp-de'],
        optional: ['aws-da'],
        skills: ['Snowflake architecture','Virtual warehouses','Data sharing','Performance tuning','Security'],
        careerOutcome: 'Essential for Snowflake-heavy orgs; growing demand in analytics engineering',
        jobRoles: ['Analytics Engineer', 'Data Engineer', 'BI Developer'],
        avgSalary: '₹10–18 LPA',
    },

    // ──────────────── DEVOPS ────────────────
    'terraform': {
        id: 'terraform',
        name: 'HashiCorp Terraform Associate',
        issuer: 'HashiCorp',
        domain: 'devops',
        level: 2,
        durationMonths: 1,
        cost: '$70',
        examCode: '003',
        prerequisites: [],
        next: ['cka', 'aws-dop'],
        advanced: ['terraform-pro'],
        optional: ['aws-sec'],
        skills: ['HCL language','State management','Modules','Workspaces','Provider ecosystem'],
        careerOutcome: 'IaC foundation cert; required in >70% of DevOps/Platform job descriptions',
        jobRoles: ['DevOps Engineer', 'Platform Engineer', 'Cloud Engineer'],
        avgSalary: '₹10–20 LPA',
    },
    'cka': {
        id: 'cka',
        name: 'Certified Kubernetes Administrator',
        issuer: 'CNCF / Linux Foundation',
        domain: 'devops',
        level: 3,
        durationMonths: 2,
        cost: '$395',
        examCode: 'CKA',
        prerequisites: [],
        next: ['cks', 'ckad'],
        advanced: [],
        optional: ['aws-dop'],
        skills: ['Cluster installation','Workloads','Services & networking','Storage','Troubleshooting'],
        careerOutcome: 'Most in-demand container platform cert; opens platform and SRE roles',
        jobRoles: ['Kubernetes Admin', 'Platform Engineer', 'SRE'],
        avgSalary: '₹14–25 LPA',
    },
    'ckad': {
        id: 'ckad',
        name: 'Certified Kubernetes Application Developer',
        issuer: 'CNCF / Linux Foundation',
        domain: 'devops',
        level: 2,
        durationMonths: 2,
        cost: '$395',
        examCode: 'CKAD',
        prerequisites: [],
        next: ['cka'],
        advanced: ['cks'],
        optional: ['terraform'],
        skills: ['Pod design','Configuration','Observability','Services & networking','State persistence'],
        careerOutcome: 'Developer-focused K8s cert; useful for backend & full-stack engineers',
        jobRoles: ['Application Developer', 'Backend Engineer', 'Cloud-Native Developer'],
        avgSalary: '₹12–20 LPA',
    },
    'cks': {
        id: 'cks',
        name: 'Certified Kubernetes Security Specialist',
        issuer: 'CNCF / Linux Foundation',
        domain: 'devops',
        level: 4,
        durationMonths: 2,
        cost: '$395',
        examCode: 'CKS',
        prerequisites: ['cka'],
        next: [],
        advanced: [],
        optional: ['cissp'],
        skills: ['Cluster hardening','Supply chain security','Runtime security','Network policies','Falco/OPA'],
        careerOutcome: 'Expert-level K8s security; leads container security programs',
        jobRoles: ['Security Engineer', 'Platform Security Lead', 'DevSecOps Engineer'],
        avgSalary: '₹18–32 LPA',
    },

    // ──────────────── WEB DEV ────────────────
    'meta-fe': {
        id: 'meta-fe',
        name: 'Meta Front-End Developer',
        issuer: 'Meta (Coursera)',
        domain: 'webdev',
        level: 1,
        durationMonths: 7,
        cost: 'Free–$49/mo',
        examCode: 'Professional Cert',
        prerequisites: [],
        next: ['meta-be'],
        advanced: ['awsdva'],
        optional: ['gcp-ace'],
        skills: ['HTML/CSS','JavaScript','React','UI/UX principles','Bootstrap','Version control'],
        careerOutcome: 'Strong portfolio foundation; opens junior front-end roles within 6–12 months',
        jobRoles: ['Front-End Developer', 'UI Engineer', 'React Developer'],
        avgSalary: '₹4–10 LPA',
    },
    'meta-be': {
        id: 'meta-be',
        name: 'Meta Back-End Developer',
        issuer: 'Meta (Coursera)',
        domain: 'webdev',
        level: 2,
        durationMonths: 9,
        cost: 'Free–$49/mo',
        examCode: 'Professional Cert',
        prerequisites: ['meta-fe'],
        next: ['aws-dva'],
        advanced: ['aws-saa'],
        optional: ['databricks-de'],
        skills: ['Python/Django','REST APIs','MySQL','Version control','Cloud deployment basics'],
        careerOutcome: 'Full-stack readiness; combine with AWS DVA for cloud-native backend roles',
        jobRoles: ['Backend Developer', 'Full-Stack Engineer', 'API Developer'],
        avgSalary: '₹6–14 LPA',
    },
    'aws-dva': {
        id: 'aws-dva',
        name: 'AWS Developer Associate',
        issuer: 'Amazon Web Services',
        domain: 'webdev',
        level: 2,
        durationMonths: 2,
        cost: '$150',
        examCode: 'DVA-C02',
        prerequisites: ['aws-ccp'],
        next: ['aws-dop', 'aws-saa'],
        advanced: ['aws-sap'],
        optional: ['terraform'],
        skills: ['Lambda','API Gateway','DynamoDB','CodePipeline','CloudFormation','SDK usage'],
        careerOutcome: 'Cloud-native development; bridges software engineering with cloud architecture',
        jobRoles: ['Cloud Developer', 'Full-Stack Engineer', 'Serverless Developer'],
        avgSalary: '₹10–18 LPA',
    },

    // ──────────────── AI/ML ────────────────
    'ibm-ds': {
        id: 'ibm-ds',
        name: 'IBM Data Science Professional Certificate',
        issuer: 'IBM (Coursera)',
        domain: 'aiml',
        level: 1,
        durationMonths: 11,
        cost: 'Free–$49/mo',
        examCode: 'Professional Cert',
        prerequisites: [],
        next: ['tf-dev', 'gcp-mle'],
        advanced: ['aws-mls'],
        optional: ['databricks-de'],
        skills: ['Python','Data analysis','SQL','Machine learning basics','Data visualization','Jupyter'],
        careerOutcome: 'Industry-recognised entry into data science; used widely in India for first DS jobs',
        jobRoles: ['Junior Data Scientist', 'Data Analyst', 'ML Engineer (Entry)'],
        avgSalary: '₹6–12 LPA',
    },
    'tf-dev': {
        id: 'tf-dev',
        name: 'TensorFlow Developer Certificate',
        issuer: 'Google',
        domain: 'aiml',
        level: 2,
        durationMonths: 3,
        cost: '$100',
        examCode: 'TF-Dev',
        prerequisites: ['ibm-ds'],
        next: ['gcp-mle'],
        advanced: ['aws-mls'],
        optional: ['databricks-de'],
        skills: ['Deep learning','CNNs & RNNs','NLP with TF','Image classification','Model deployment'],
        careerOutcome: 'Validates hands-on DL skills; strong signal for ML engineer roles',
        jobRoles: ['ML Engineer', 'Deep Learning Engineer', 'AI Developer'],
        avgSalary: '₹10–20 LPA',
    },
    'gcp-mle': {
        id: 'gcp-mle',
        name: 'Google Professional ML Engineer',
        issuer: 'Google Cloud',
        domain: 'aiml',
        level: 3,
        durationMonths: 3,
        cost: '$200',
        examCode: 'PMLE',
        prerequisites: ['tf-dev', 'gcp-ace'],
        next: [],
        advanced: [],
        optional: ['aws-mls'],
        skills: ['ML problem framing','Data preparation','Model development','MLOps','Responsible AI'],
        careerOutcome: 'Senior ML engineering roles; leads end-to-end AI product delivery on GCP',
        jobRoles: ['ML Engineer', 'AI/ML Architect', 'MLOps Engineer'],
        avgSalary: '₹18–35 LPA',
    },
    'aws-mls': {
        id: 'aws-mls',
        name: 'AWS Machine Learning Specialty',
        issuer: 'Amazon Web Services',
        domain: 'aiml',
        level: 3,
        durationMonths: 3,
        cost: '$300',
        examCode: 'MLS-C01',
        prerequisites: ['aws-saa', 'ibm-ds'],
        next: [],
        advanced: [],
        optional: ['gcp-mle'],
        skills: ['SageMaker','Data engineering for ML','Modelling','ML implementation & ops','Evaluation'],
        careerOutcome: 'Cloud ML specialist; opens AI platform and MLOps architect roles on AWS',
        jobRoles: ['ML Engineer (AWS)', 'MLOps Engineer', 'AI Product Engineer'],
        avgSalary: '₹16–30 LPA',
    },
};

// Build a node → level mapping per domain for visual rendering
export function buildDomainGraph(domainId, ownedCertIds = []) {
    const owned = new Set(ownedCertIds);
    const certs = Object.values(CERT_DB).filter(c => c.domain === domainId);
    const maxLevel = Math.max(...certs.map(c => c.level));

    const levels = [];
    for (let l = 1; l <= maxLevel; l++) {
        const row = certs.filter(c => c.level === l).map(c => ({
            ...c,
            owned: owned.has(c.id),
            unlocked: c.prerequisites.length === 0 || c.prerequisites.some(p => owned.has(p)),
        }));
        if (row.length) levels.push(row);
    }
    return levels;
}

export function generateSmartRoadmap(ownedCertIds = [], targetDomainId = null) {
    const owned = new Set(ownedCertIds);
    const allCerts = Object.values(CERT_DB);

    // Directly-unlocked next steps
    const unlocked = allCerts.filter(c =>
        !owned.has(c.id) &&
        c.prerequisites.length > 0 &&
        c.prerequisites.some(p => owned.has(p))
    );

    // New starter picks per domain
    const starters = targetDomainId
        ? allCerts.filter(c =>
            c.domain === targetDomainId &&
            c.prerequisites.length === 0 &&
            !owned.has(c.id)
        )
        : [];

    // Skill gaps = certs listed as 'next' or 'advanced' from owned certs
    const gapIds = new Set();
    ownedCertIds.forEach(id => {
        const rule = CERT_DB[id];
        if (!rule) return;
        [...rule.next, ...rule.advanced].forEach(n => { if (!owned.has(n)) gapIds.add(n); });
    });
    const skillGaps = [...gapIds].map(id => CERT_DB[id]).filter(Boolean);

    return {
        ownedCerts: ownedCertIds.map(id => CERT_DB[id]).filter(Boolean),
        recommended: unlocked.slice(0, 6),
        starters: starters.slice(0, 4),
        skillGaps: skillGaps.slice(0, 6),
    };
}
